### ISSUE TITLE
Disable send buttons when exceeding maxCarbs or maxBolus?

### ISSUE THREAD

**Issue by dsnallfot** [dsnallfot/LoopFollowiAPS#68]
Another example of UI/UX change in my special branch - Do we want this in dev-remote also?

| maxBolus exceeded in meal view | maxCarbs exceeded in meal view | maxBolus exceeded in Bolus view |
|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 10 34](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/38c29ec1-300d-48e9-8720-aa2c27c3acec) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 10 27](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/00b2c678-1587-4137-b32e-45b37ffb5a86) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 10 43](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/d214e044-d4f6-43db-bd06-44d035180150) | 

I also use the same "maxCarbs" threshold for fat and protein entries (instead of using 3 different maxCarbs, maxFat, maxProtein guardrails

| Fat exceeding maxCarbs | Protein exceeding maxCarbs |
|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 17 30](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/c8d25d94-15e1-4cfa-86af-188f46536aae) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 17 35](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/c139f16e-fa0d-4e14-b128-7e4c82edbc53) |

**Comment by aug0211** [comment]
I like parts, and not others. The general idea of blocking the action button is fantastic of course, and using visual cues seems very good (graying out submit button and listing the safety guard that was surpassed).

What do you think about changing the "offending" cell to a red highlight when it surpasses the threshold? Eg, if max carbs = 20, and carbs entered = 30, highlight the carbs cell in red tint, so it is very easy to see where the issue is.

One part I am not a fan of - max carbs being applied to fat, and protein. I can see the logic in doing this, but I don't think it's quite right. We have meals where fat or protein are higher than carbs - not all that rare for this to happen for us. For some who do low carb diets (we were pretty strictly low carb for a good period of time), this could be problematic.

Example - grilled chicken wing night. You might end up with something like ~10 carbs, 40 fat, 60 protein (ballparks). If a low carb eater keeps carbs under 20g as a rule, maybe their max carb is set to... 30. In this instance, both fat and protein would exceed.

^my numbers above are swags but we recently had wings and I recall it being something like this.

**Comment by dsnallfot** [comment]
Good points.

The main use case for any nutrition guardrail I think is to prevent accidentally typing for instance 2000 or 200 grams when meaning to type 20 grams. And for that purpose I did not see that the guardrails needed to take different kinds of diets into account. But your low carb example is a good one that needs consideration. 

I can see a few different approaches to solve this "using maxcarbs for fat/protein entries" part. 

1. Simply give the guardrail another name ("Max nutrition grams" or something. You can set that to whatever suits your needs (best practice = use the max amount you usually enter for any of the macronutrients). 

2. Add another (or two more) guardrail in settings. Ie one for maxcarbs and another for max fat/max protein?

3. Allow any amount of fat/protein by default and only guard carbs. The risk of smb overdosing in iAPS because of erroneously high amounts fat/protein entered is lower and not as direct as with erroneous carb entries. 


Let's decide on approach 1,2 or 3 above, and then I can look into color coding offending entries also - which I think is a great idea

**Comment by dsnallfot** [comment]
Ok, just tried this approach in my special branch. Added a setting for max fat or protein, and customized the text on the disabled button based on which entry that is the offending one (that way its maybe not necessary to conditionally format the offending cell red? - that could also be done of course, but its a bit tricky to get right due to all things in that view already listening for different real time changes in the entries fields).

Sorry for Swedish in the screenshots, but I think you get the point  :)

| Setting | Max carb | MaxFP | Max Bolus |
|--------|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-04-21 at 11 00 27](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/1f4ada00-6ef5-43d3-b071-9ba0afe2fc5b) | ![Simulator Screenshot - iPhone 13 - 2024-04-21 at 10 59 27](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/a12a008f-da79-4be6-85b1-92c8e2c7aadd) | ![Simulator Screenshot - iPhone 13 - 2024-04-21 at 10 59 36](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/ff8e19b5-0e90-455e-b02b-288d7d39ccb8) | ![Simulator Screenshot - iPhone 13 - 2024-04-21 at 11 10 21](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/02fcc944-ce64-4fb1-a9d8-0ad7972ce2d8) |

**Comment by aug0211** [comment]
**I think this is good and probably the right thing.**

I _personally_ would go for a specific guard rail for each item, so I could set X for fat and Y for protein, because on principle I _want_ to think they're different.

But here's the kicker, I have absolutely no idea what they should actually be 😂 Other than like you said, avoiding fat fingering an extra digit to increase by an order of magnitude. **I'd probably end up setting both at the same thing, anyway** (though I do still think it's _valuable to differentiate from carbs like you've done)._

The button update looks good and is clear, I don't know about the red shading I mentioned before. Maybe that'd be cool one day to play with but also, maybe that's getting into _too busy_ territory.

**What you have now is I think the right level of detail without too much extra "noise"** - on both fronts (how many unique guard rails, how many visual lights to flash when something is off).

**Comment by dsnallfot** [comment]
Great! I'll make a PR to dev-remote with this during next week.

When I were fiddeling around with the stuff above I also looked into more error handling and user notifications when something goes wrong anywhere in the flow. For instance if you should add input in the wrong format in any of the entries fields. 

If entering Carbs with an extra decimal separator or something like that, and trying to send the meal, in current implementation the send attempt fails without telling why (other than a print to log). But with an alert it gets obvious for the user what went wrong).

Example below: Carbs (Kolhydrater) 25,,5 g entered instead of the correct 25,5)
Alert displays, and says: "Error - Carbs are entered in the wrong format" and the button says "Change" (Ändra)

I've implemented this error alert for carbs, fat, protein and bolus entries, and it shows after clicking the send button if any errors are found.

However. This will be a separate suggested PR that we can discuss after the first one is in 😊 
![Simulator Screenshot - iPhone 13 - 2024-04-21 at 14 29 39](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/e56f2e99-fb15-4e14-93f4-b3114b98123f)

**Comment by dsnallfot** [comment]
All above is now in PR #70 
Closing this issue for now (New needs/tweaks->We just open a new issue)
